# -*- coding: utf-8 -*-
"""anket_uygulaması.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkC6ljH5sICU2AIUXZaFAGWrdPXFhKmu
"""

"""
=====================================================================
CİLT LEZYONU DEĞERLENDİRME ANKETİ — Streamlit
Veriler Google Apps Script üzerinden Google Sheets'e yazılır.
=====================================================================
"""

import streamlit as st
import requests, random, hashlib, json
from datetime import datetime

# ─────────────────────────────────────────────────────────────────
# CONFIG — sadece burayı doldur
# ─────────────────────────────────────────────────────────────────
GITHUB_BASE = "https://raw.githubusercontent.com/kaktasmd/tez_anket_gorseller/main/anket_gorseller/"
MANIFEST_URL = GITHUB_BASE + "manifest.json"
PREDICTIONS_URL = GITHUB_BASE + "predictions.json"

APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbypn-0lMNxwgQT_0UTZ-EmIWMCgJvpR_Te0RsEPS7Y2chnJe_8VBPDCqYNYD3Bm1887dQ/exec"

STUDY_TITLE = "Cilt Lezyonu Değerlendirme Çalışması"
YEAR_OPTIONS = ["1. yıl", "2. yıl", "3. yıl", "4. yıl", "5. yıl", "6. yıl ve üzeri"]
CLASS_LABELS = {
    "NEVUS": "Nevüs",
    "KERATOZ": "Keratoz",
    "MELANOM": "Melanom",
    "NMSC": "NMSC",
    "DISPLASTIK_NEVUS": "Displastik Nevüs",
}

# Kurum adında geçmesi gereken anahtar kelimeler
INSTITUTION_KEYWORDS = ["üniversite", "universite", "hastane", "hastanesi", "üniversitesi"]


# ─────────────────────────────────────────────────────────────────
# YARDIMCI FONKSİYONLAR
# ─────────────────────────────────────────────────────────────────
def email_hash(email):
    return hashlib.sha256(email.strip().lower().encode()).hexdigest()


def is_valid_institution(text):
    t = text.strip().lower()
    if len(t) < 3:
        return False
    return any(kw in t for kw in INSTITUTION_KEYWORDS)


def build_key(item):
    return item["class"] + "/" + item["file"]


# ─────────────────────────────────────────────────────────────────
# APPS SCRIPT ÇAĞRILARI
# ─────────────────────────────────────────────────────────────────
def get_email_status(ehash):
    try:
        r = requests.get(APPS_SCRIPT_URL, params={"action": "check_email", "hash": ehash}, timeout=15)
        r.raise_for_status()
        return r.json()
    except Exception as e:
        st.error(f"Sunucuya bağlanılamadı: {e}")
        return {"completed": False, "resume": False}


def upsert_lock(ehash, participant_id, completed, year, university, image_order_json):
    try:
        requests.post(APPS_SCRIPT_URL, json={
            "action": "lock", "hash": ehash,
            "participant_id": participant_id, "completed": completed,
            "year": year, "university": university,
            "image_order": image_order_json,
        }, timeout=15)
    except Exception as e:
        st.error(f"Kayıt hatası: {e}")


def append_response(row):
    try:
        requests.post(APPS_SCRIPT_URL, json={"action": "response", "row": row}, timeout=15)
    except Exception as e:
        st.error(f"Kayıt hatası: {e}")


@st.cache_data(ttl=60)
def load_manifest():
    r = requests.get(MANIFEST_URL, timeout=15)
    r.raise_for_status()
    return r.json()  # [{"class": "...", "file": "..."}]


@st.cache_data(ttl=60)
def load_predictions():
    try:
        r = requests.get(PREDICTIONS_URL, timeout=15)
        r.raise_for_status()
        return r.json()
    except Exception:
        return {}


# ─────────────────────────────────────────────────────────────────
# STATE
# ─────────────────────────────────────────────────────────────────
if "screen" not in st.session_state:
    st.session_state.screen = "welcome"
if "idx" not in st.session_state:
    st.session_state.idx = 0
if "demo_warning" not in st.session_state:
    st.session_state.demo_warning = ""

st.set_page_config(page_title=STUDY_TITLE, page_icon="🩺", layout="centered")

# ─────────────────────────────────────────────────────────────────
# WELCOME
# ─────────────────────────────────────────────────────────────────
if st.session_state.screen == "welcome":
    st.title(STUDY_TITLE)

    st.markdown(
        "Bu anket, **derin öğrenme tabanlı bir yapay zeka modelinin** cilt lezyonu "
        "sınıflandırmasındaki tanı performansını, **dermatoloji asistan hekimlerinin** "
        "klinik değerlendirmesiyle karşılaştırmayı amaçlayan bir tez çalışmasının parçasıdır."
    )

    st.markdown("#### Nasıl işleyecek?")
    st.markdown(
        "- Sırayla **150 dermatoskopik görüntü** göreceksiniz (rastgele sırayla).\n"
        "- Her görüntü için, aşağıdaki **5 tanı sınıfından birini** seçeceksiniz.\n"
        "- Ardından bu tanıya **ne kadar emin olduğunuzu 0–10 arası** puanlayacaksınız "
        "(0 = tahmine yakın, 10 = tamamen eminim).\n"
        "- Cevabınızı verdikten sonra bir sonraki görüntüye otomatik geçilecek."
    )

    with st.expander("Değerlendirilecek 5 tanı sınıfı"):
        st.markdown(
            "- **Nevüs** — benign melanositik nevüs\n"
            "- **Keratoz** — seboreik / aktinik keratoz\n"
            "- **Melanom** — malign melanom\n"
            "- **NMSC** — melanom dışı deri kanseri (bazal hücreli / skuamöz hücreli karsinom)\n"
            "- **Displastik Nevüs** — atipik / displastik nevüs"
        )

    st.markdown("#### Süre ve gizlilik")
    st.markdown(
        "- Ortalama süre **20–25 dakika**.\n"
        "- Cevaplarınız **anonim** olarak analiz edilecektir; sonuç raporlarında kimlik "
        "bilgisi yer almayacaktır.\n"
        "- E-posta adresiniz **yalnızca** aynı kişinin anketi birden fazla doldurmasını "
        "engellemek için kullanılır, analizde görünmez.\n"
        "- Anketi yarıda bırakırsanız cevaplarınız kaybolmaz; aynı e-posta ile devam "
        "ettiğinizde kaldığınız sorudan, aynı sırayla devam edersiniz."
    )

    st.markdown(
        "Katılımınız tamamen gönüllülük esasına dayanmaktadır ve bilimsel bir çalışmaya "
        "sağlayacağınız katkı için şimdiden teşekkür ederiz."
    )

    if st.button("Ankete Başla →", use_container_width=True):
        st.session_state.screen = "demographics"
        st.rerun()

# ─────────────────────────────────────────────────────────────────
# DEMOGRAPHICS
# ─────────────────────────────────────────────────────────────────
elif st.session_state.screen == "demographics":
    st.header("Önce birkaç bilgi")
    year = st.selectbox("Asistanlıkta kaçıncı yılındasınız?", [""] + YEAR_OPTIONS)
    university = st.text_input(
        "Hangi üniversitede/hastanede tıp eğitimi aldınız / ihtisas yapıyorsunuz?",
        placeholder="Örn. Süleyman Demirel Üniversitesi ya da XY Eğitim Araştırma Hastanesi",
    )
    email = st.text_input("E-posta adresiniz")

    if st.session_state.demo_warning:
        st.warning(st.session_state.demo_warning)

    if st.button("Devam Et →", use_container_width=True):
        st.session_state.demo_warning = ""

        if not (year and university.strip() and email.strip()):
            st.error("Lütfen tüm alanları doldurun.")
        elif "@" not in email or "." not in email.split("@")[-1]:
            st.error("Geçerli bir e-posta adresi girin.")
        elif not is_valid_institution(university):
            st.error(
                "Kurum adı geçerli görünmüyor. Lütfen adında 'Üniversite' ya da 'Hastane' "
                "ifadesi geçen tam kurum adını yazın (örn. 'Ankara Üniversitesi', "
                "'XY Eğitim ve Araştırma Hastanesi')."
            )
        else:
            with st.spinner("Kontrol ediliyor…"):
                ehash = email_hash(email)
                status = get_email_status(ehash)

                if status.get("completed"):
                    st.session_state.screen = "blocked"
                    st.rerun()

                elif status.get("resume"):
                    stored_year = status.get("year", "")
                    stored_university = status.get("university", "")

                    mismatch_notes = []
                    if stored_year and stored_year != year:
                        mismatch_notes.append(f"kıdem yılı ('{stored_year}' olarak kayıtlıydı, '{year}' girdiniz)")
                    if stored_university and stored_university != university.strip():
                        mismatch_notes.append(f"kurum adı ('{stored_university}' olarak kayıtlıydı)")

                    if mismatch_notes:
                        st.session_state.demo_warning = (
                            "Bu e-posta ile daha önce farklı bilgilerle kayıt oluşturulmuş: "
                            + "; ".join(mismatch_notes)
                            + ". Tutarlılık için orijinal bilgileriniz kullanılarak devam edilecek."
                        )
                        st.rerun()

                    manifest = load_manifest()
                    by_key = {build_key(it): it for it in manifest}
                    order_keys = json.loads(status.get("image_order") or "[]")
                    answered = set(status.get("answered_images", []))
                    remaining_keys = [k for k in order_keys if k not in answered]
                    remaining_items = [by_key[k] for k in remaining_keys if k in by_key]

                    st.session_state.images = remaining_items
                    st.session_state.total_questions = len(order_keys) if order_keys else len(manifest)
                    st.session_state.answered_offset = len(answered)
                    st.session_state.participant_id = status["participant_id"]
                    st.session_state.email_hash = ehash
                    st.session_state.image_order_json = status.get("image_order") or "[]"
                    st.session_state.demographics = {
                        "year": stored_year or year,
                        "university": stored_university or university.strip(),
                    }
                    st.session_state.idx = 0
                    st.session_state.demo_warning = ""
                    st.session_state.screen = "survey"
                    st.rerun()

                else:
                    manifest = load_manifest()
                    images = manifest.copy()
                    random.shuffle(images)
                    order_json = json.dumps([build_key(it) for it in images])

                    st.session_state.images = images
                    st.session_state.total_questions = len(manifest)
                    st.session_state.answered_offset = 0
                    st.session_state.participant_id = ehash[:10] + "-" + datetime.now().strftime("%H%M%S")
                    st.session_state.email_hash = ehash
                    st.session_state.image_order_json = order_json
                    st.session_state.demographics = {"year": year, "university": university.strip()}
                    st.session_state.idx = 0

                    upsert_lock(ehash, st.session_state.participant_id, False, year, university.strip(), order_json)
                    st.session_state.screen = "survey"
                    st.rerun()

# ─────────────────────────────────────────────────────────────────
# BLOCKED
# ─────────────────────────────────────────────────────────────────
elif st.session_state.screen == "blocked":
    st.header("Bu anket zaten tamamlanmış.")
    st.write(
        "Girdiğiniz e-posta adresiyle daha önce bir kayıt tamamlanmış görünüyor. "
        "Her katılımcı anketi yalnızca bir kez doldurabilir."
    )

# ─────────────────────────────────────────────────────────────────
# SURVEY
# ─────────────────────────────────────────────────────────────────
elif st.session_state.screen == "survey":
    remaining_total = len(st.session_state.images)
    idx = st.session_state.idx
    item = st.session_state.images[idx]
    key = build_key(item)
    url = GITHUB_BASE + key

    total = st.session_state.total_questions
    offset = st.session_state.answered_offset
    question_number = offset + idx + 1
    is_last = idx == remaining_total - 1

    st.progress((offset + idx) / total)
    st.caption(f"Soru {question_number} / {total}")
    st.image(url, use_container_width=True)

    if not st.session_state.get("reveal", False):
        choice = st.radio(
            "Bu lezyon için tanınız nedir?",
            list(CLASS_LABELS.keys()),
            format_func=lambda k: CLASS_LABELS[k],
            index=None,
            key=f"choice_{idx}",
        )
        confidence = st.slider("Bu tanıya ne kadar eminsiniz?", 0, 10, value=5, key=f"conf_{idx}")

        if st.button("Cevapla", use_container_width=True, disabled=(choice is None)):
            d = st.session_state.demographics
            row = [
                st.session_state.participant_id, st.session_state.email_hash,
                d["year"], d["university"], question_number, key,
                item["class"], choice, choice == item["class"], confidence,
                datetime.now().isoformat(),
            ]
            append_response(row)
            st.session_state.last_choice = choice
            st.session_state.last_confidence = confidence
            st.session_state.reveal = True
            st.rerun()

    else:
        preds = load_predictions()
        pred = preds.get(key)

        st.markdown("---")
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**Sizin cevabınız**")
            st.write(CLASS_LABELS.get(st.session_state.last_choice, st.session_state.last_choice))
            st.caption(f"Emin olma: {st.session_state.last_confidence}/10")
        with col2:
            st.markdown("**Modelin tahmini**")
            if pred:
                st.write(CLASS_LABELS.get(pred["predicted_class"], pred["predicted_class"]))
                st.caption(f"Olasılık: %{pred['confidence']}")
            else:
                st.write("_Veri bulunamadı_")

        if st.button("Anketi Bitir" if is_last else "Sonraki Soru →", use_container_width=True):
            st.session_state.reveal = False
            if not is_last:
                st.session_state.idx += 1
                st.rerun()
            else:
                d = st.session_state.demographics
                upsert_lock(
                    st.session_state.email_hash, st.session_state.participant_id, True,
                    d["year"], d["university"], st.session_state.image_order_json,
                )
                st.session_state.screen = "finished"
                st.rerun()

# ─────────────────────────────────────────────────────────────────
# FINISHED
# ─────────────────────────────────────────────────────────────────
elif st.session_state.screen == "finished":
    st.success("Teşekkürler! 150 değerlendirmeniz kaydedildi.")
    st.caption(f"Kayıt kodu: {st.session_state.get('participant_id', '')}")