# -*- coding: utf-8 -*-
"""anket_uygulaması.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkC6ljH5sICU2AIUXZaFAGWrdPXFhKmu
"""

"""
=====================================================================
CİLT LEZYONU DEĞERLENDİRME ANKETİ — Streamlit
Veriler Google Apps Script üzerinden Google Sheets'e yazılır.
Service account / Cloud Console gerektirmez.
=====================================================================
"""

import streamlit as st
import requests, random, hashlib
from datetime import datetime

# ─────────────────────────────────────────────────────────────────
# CONFIG — sadece burayı doldur
# ─────────────────────────────────────────────────────────────────
GITHUB_BASE = "https://raw.githubusercontent.com/kaktasmd/tez_anket_gorseller/main/anket_gorseller/"
MANIFEST_URL = GITHUB_BASE + "manifest.json"

# Apps Script'i deploy edince aldığın Web App URL'i buraya yapıştır
APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbypn-0lMNxwgQT_0UTZ-EmIWMCgJvpR_Te0RsEPS7Y2chnJe_8VBPDCqYNYD3Bm1887dQ/exec"

STUDY_TITLE = "Cilt Lezyonu Değerlendirme Çalışması"
YEAR_OPTIONS = ["< 2 sene","2-4 sene","> 4 sene"]
CLASS_LABELS = {
    "NEVUS": "Nevüs",
    "KERATOZ": "Keratoz",
    "MELANOM": "Melanom",
    "NMSC": "NMSC",
    "DISPLASTIK_NEVUS": "Displastik Nevüs",
}

# ─────────────────────────────────────────────────────────────────
# APPS SCRIPT ÇAĞRILARI
# ─────────────────────────────────────────────────────────────────
def is_email_completed(ehash):
    try:
        r = requests.get(APPS_SCRIPT_URL, params={"action": "check_email", "hash": ehash}, timeout=15)
        r.raise_for_status()
        return bool(r.json().get("completed", False))
    except Exception as e:
        st.error(f"Sunucuya bağlanılamadı: {e}")
        return False


def upsert_lock(ehash, participant_id, completed):
    try:
        requests.post(APPS_SCRIPT_URL, json={
            "action": "lock", "hash": ehash,
            "participant_id": participant_id, "completed": completed,
        }, timeout=15)
    except Exception as e:
        st.error(f"Kayıt hatası: {e}")


def append_response(row):
    try:
        requests.post(APPS_SCRIPT_URL, json={"action": "response", "row": row}, timeout=15)
    except Exception as e:
        st.error(f"Kayıt hatası: {e}")


@st.cache_data(ttl=60)
def load_manifest():
    r = requests.get(MANIFEST_URL, timeout=15)
    r.raise_for_status()
    return r.json()  # [{"class": "...", "file": "..."}]


def email_hash(email):
    return hashlib.sha256(email.strip().lower().encode()).hexdigest()


# ─────────────────────────────────────────────────────────────────
# STATE
# ─────────────────────────────────────────────────────────────────
if "screen" not in st.session_state:
    st.session_state.screen = "welcome"
if "answers" not in st.session_state:
    st.session_state.answers = []
if "idx" not in st.session_state:
    st.session_state.idx = 0

st.set_page_config(page_title=STUDY_TITLE, page_icon="🩺", layout="centered")

# ─────────────────────────────────────────────────────────────────
# WELCOME
# ─────────────────────────────────────────────────────────────────
if st.session_state.screen == "welcome":
    st.title(STUDY_TITLE)
    st.write(
        "150 dermatoskopik görüntüyü değerlendireceksiniz. Her görüntü için 5 tanı "
        "seçeneğinden birini işaretleyip, tanınıza ne kadar emin olduğunuzu 0–10 arası "
        "puanlayacaksınız."
    )
    st.caption(
        "Cevaplarınız anonim olarak analiz edilecektir; e-posta adresiniz yalnızca "
        "mükerrer katılımı engellemek için kullanılır."
    )
    if st.button("Ankete Başla →", use_container_width=True):
        st.session_state.screen = "demographics"
        st.rerun()

# ─────────────────────────────────────────────────────────────────
# DEMOGRAPHICS
# ─────────────────────────────────────────────────────────────────
elif st.session_state.screen == "demographics":
    st.header("Önce birkaç bilgi")
    year = st.selectbox("Asistanlıkta kaçıncı yılındasınız?", [""] + YEAR_OPTIONS)
    university = st.text_input("Hangi üniversitede tıp eğitimi aldınız / ihtisas yapıyorsunuz?")
    email = st.text_input("E-posta adresiniz")

    if st.button("Devam Et →", use_container_width=True):
        if not (year and university.strip() and email.strip()):
            st.error("Lütfen tüm alanları doldurun.")
        elif "@" not in email or "." not in email.split("@")[-1]:
            st.error("Geçerli bir e-posta adresi girin.")
        else:
            with st.spinner("Kontrol ediliyor…"):
                ehash = email_hash(email)
                if is_email_completed(ehash):
                    st.session_state.screen = "blocked"
                    st.rerun()
                else:
                    manifest = load_manifest()
                    images = manifest.copy()
                    random.shuffle(images)
                    st.session_state.images = images
                    st.session_state.participant_id = ehash[:10] + "-" + datetime.now().strftime("%H%M%S")
                    st.session_state.email_hash = ehash
                    st.session_state.demographics = {"year": year, "university": university.strip()}
                    st.session_state.idx = 0
                    st.session_state.answers = []
                    upsert_lock(ehash, st.session_state.participant_id, False)
                    st.session_state.screen = "survey"
                    st.rerun()

# ─────────────────────────────────────────────────────────────────
# BLOCKED
# ─────────────────────────────────────────────────────────────────
elif st.session_state.screen == "blocked":
    st.header("Bu anket zaten tamamlanmış.")
    st.write(
        "Girdiğiniz e-posta adresiyle daha önce bir kayıt tamamlanmış görünüyor. "
        "Her katılımcı anketi yalnızca bir kez doldurabilir."
    )

# ─────────────────────────────────────────────────────────────────
# SURVEY
# ─────────────────────────────────────────────────────────────────
elif st.session_state.screen == "survey":
    total = len(st.session_state.images)
    idx = st.session_state.idx
    item = st.session_state.images[idx]
    url = GITHUB_BASE + item["class"] + "/" + item["file"]

    st.progress(idx / total)
    st.caption(f"Soru {idx + 1} / {total}")
    st.image(url, use_container_width=True)

    choice = st.radio(
        "Bu lezyon için tanınız nedir?",
        list(CLASS_LABELS.keys()),
        format_func=lambda k: CLASS_LABELS[k],
        index=None,
        key=f"choice_{idx}",
    )
    confidence = st.slider("Bu tanıya ne kadar eminsiniz?", 0, 10, value=5, key=f"conf_{idx}")

    label = "Anketi Bitir" if idx == total - 1 else "İleri →"
    if st.button(label, use_container_width=True, disabled=(choice is None)):
        d = st.session_state.demographics
        row = [
            st.session_state.participant_id, st.session_state.email_hash,
            d["year"], d["university"], idx + 1, item["class"] + "/" + item["file"],
            item["class"], choice, choice == item["class"], confidence,
            datetime.now().isoformat(),
        ]
        append_response(row)

        if idx < total - 1:
            st.session_state.idx += 1
            st.rerun()
        else:
            upsert_lock(st.session_state.email_hash, st.session_state.participant_id, True)
            st.session_state.screen = "finished"
            st.rerun()

# ─────────────────────────────────────────────────────────────────
# FINISHED
# ─────────────────────────────────────────────────────────────────
elif st.session_state.screen == "finished":
    st.success("Teşekkürler! 150 değerlendirmeniz kaydedildi.")
    st.caption(f"Kayıt kodu: {st.session_state.get('participant_id', '')}")